version: "3"

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:
